// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wizards.Infrastructure.Persistence;

#nullable disable

namespace Wizards.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815040332_AddEventRegistrationIdempotencyKeys")]
    partial class AddEventRegistrationIdempotencyKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistrationLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("StartDateTime", "Id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.EventGameTypeSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Key")
                        .IsUnique();

                    b.ToTable("event_game_type_selections", (string)null);
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.EventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("EventId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("event_registrations", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("game_types", (string)null);
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.GameTypeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId", "Key")
                        .IsUnique();

                    b.ToTable("game_type_settings", (string)null);
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.GameTypeSettingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeSettingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeSettingId", "Value")
                        .IsUnique();

                    b.ToTable("game_type_setting_options", (string)null);
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.Event", b =>
                {
                    b.HasOne("Wizards.Infrastructure.Persistence.Records.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.EventGameTypeSelection", b =>
                {
                    b.HasOne("Wizards.Infrastructure.Persistence.Records.Event", "Event")
                        .WithMany("Selections")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.EventRegistration", b =>
                {
                    b.HasOne("Wizards.Infrastructure.Persistence.Records.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.GameTypeSetting", b =>
                {
                    b.HasOne("Wizards.Infrastructure.Persistence.Records.GameType", "GameType")
                        .WithMany("Settings")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.GameTypeSettingOption", b =>
                {
                    b.HasOne("Wizards.Infrastructure.Persistence.Records.GameTypeSetting", "Setting")
                        .WithMany("Options")
                        .HasForeignKey("GameTypeSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setting");
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.Event", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.GameType", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Wizards.Infrastructure.Persistence.Records.GameTypeSetting", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
